#ifndef COMSETDIALOG_H_INCLUDED
#define COMSETDIALOG_H_INCLUDED

#define COMSTAT_DLG_WIDTH       500
#define COMSTAT_DLG_HEIGHT      500

#define COMSTAT_TITLE_HIGHT     80

void show_comset_dialog();

#endif // COMSETDIALOG_H_INCLUDED
